app:
  build: .
  links:
   - rethinkdb
  ports:
   - "3000:8000"
  environment:
   - VIRTUAL_HOST=rethinktags.dalanmiller.com
  restart: always

rethinkdb:
  restart: always
  image: rethinkdb
  ports:
   - "10001:8080"
   - "10002:28015"
   - "10003:29015"
 
